// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: options.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Option:
	//	*MessageOption_Disable
	//	*MessageOption_ToString
	//	*MessageOption_Custom
	Option isMessageOption_Option `protobuf_oneof:"option"`
}

// Default values for MessageOption fields.
const (
	Default_MessageOption_Disable = bool(false)
)

func (x *MessageOption) Reset() {
	*x = MessageOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOption) ProtoMessage() {}

func (x *MessageOption) ProtoReflect() protoreflect.Message {
	mi := &file_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOption.ProtoReflect.Descriptor instead.
func (*MessageOption) Descriptor() ([]byte, []int) {
	return file_options_proto_rawDescGZIP(), []int{0}
}

func (m *MessageOption) GetOption() isMessageOption_Option {
	if m != nil {
		return m.Option
	}
	return nil
}

func (x *MessageOption) GetDisable() bool {
	if x, ok := x.GetOption().(*MessageOption_Disable); ok {
		return x.Disable
	}
	return Default_MessageOption_Disable
}

func (x *MessageOption) GetToString() bool {
	if x, ok := x.GetOption().(*MessageOption_ToString); ok {
		return x.ToString
	}
	return false
}

func (x *MessageOption) GetCustom() *MessageOption_CustomStarlark {
	if x, ok := x.GetOption().(*MessageOption_Custom); ok {
		return x.Custom
	}
	return nil
}

type isMessageOption_Option interface {
	isMessageOption_Option()
}

type MessageOption_Disable struct {
	// Ignore the message
	Disable bool `protobuf:"varint,1,opt,name=disable,oneof,def=0"`
}

type MessageOption_ToString struct {
	// Simple convert to starlark.String
	ToString bool `protobuf:"varint,2,opt,name=to_string,json=toString,oneof"`
}

type MessageOption_Custom struct {
	// User will provide a fully custom ToStarlark method
	Custom *MessageOption_CustomStarlark `protobuf:"bytes,4,opt,name=custom,oneof"`
}

func (*MessageOption_Disable) isMessageOption_Option() {}

func (*MessageOption_ToString) isMessageOption_Option() {}

func (*MessageOption_Custom) isMessageOption_Option() {}

type MessageOption_CustomStarlark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// if empty, the package will be same as go_package option
	// if `STARLARK`, will use go.starlark.net/starlark
	// if `HELPER`, will use github.com/ImSingee/starlarkhelper
	StarlarkTypePackage *string `protobuf:"bytes,1,req,name=starlark_type_package,json=starlarkTypePackage" json:"starlark_type_package,omitempty"`
	// the name returned by `ToStarlark` method
	// if it returns pointer, starlark_type_name should start with *
	StarlarkTypeName *string `protobuf:"bytes,2,req,name=starlark_type_name,json=starlarkTypeName" json:"starlark_type_name,omitempty"`
}

func (x *MessageOption_CustomStarlark) Reset() {
	*x = MessageOption_CustomStarlark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOption_CustomStarlark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOption_CustomStarlark) ProtoMessage() {}

func (x *MessageOption_CustomStarlark) ProtoReflect() protoreflect.Message {
	mi := &file_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOption_CustomStarlark.ProtoReflect.Descriptor instead.
func (*MessageOption_CustomStarlark) Descriptor() ([]byte, []int) {
	return file_options_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MessageOption_CustomStarlark) GetStarlarkTypePackage() string {
	if x != nil && x.StarlarkTypePackage != nil {
		return *x.StarlarkTypePackage
	}
	return ""
}

func (x *MessageOption_CustomStarlark) GetStarlarkTypeName() string {
	if x != nil && x.StarlarkTypeName != nil {
		return *x.StarlarkTypeName
	}
	return ""
}

var file_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOption)(nil),
		Field:         98125,
		Name:          "protoc_gen_starlark_go.options.message_option",
		Tag:           "bytes,98125,opt,name=message_option",
		Filename:      "options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*MessageOption)(nil),
		Field:         98125,
		Name:          "protoc_gen_starlark_go.options.enum_option",
		Tag:           "bytes,98125,opt,name=enum_option",
		Filename:      "options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional protoc_gen_starlark_go.options.MessageOption message_option = 98125;
	E_MessageOption = &file_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional protoc_gen_starlark_go.options.MessageOption enum_option = 98125;
	E_EnumOption = &file_options_proto_extTypes[1]
)

var File_options_proto protoreflect.FileDescriptor

var file_options_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72,
	0x6c, 0x61, 0x72, 0x6b, 0x5f, 0x67, 0x6f, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa7, 0x02, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x3a, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x74, 0x6f, 0x5f, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x74, 0x6f, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x56, 0x0a, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f, 0x67,
	0x65, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x5f, 0x67, 0x6f, 0x2e, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x72, 0x6c,
	0x61, 0x72, 0x6b, 0x48, 0x00, 0x52, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x1a, 0x72, 0x0a,
	0x0e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x12,
	0x32, 0x0a, 0x15, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x13,
	0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x10, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x42, 0x08, 0x0a, 0x06, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x77, 0x0a, 0x0e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xcd,
	0xfe, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f,
	0x67, 0x65, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x5f, 0x67, 0x6f, 0x2e,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x6e, 0x0a, 0x0b, 0x65, 0x6e, 0x75, 0x6d, 0x5f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xcd, 0xfe, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x5f,
	0x67, 0x6f, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x6e, 0x75, 0x6d, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x49, 0x6d, 0x53, 0x69, 0x6e, 0x67, 0x65, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x73, 0x74, 0x61, 0x72, 0x6c, 0x61, 0x72, 0x6b, 0x2d,
	0x67, 0x6f, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
}

var (
	file_options_proto_rawDescOnce sync.Once
	file_options_proto_rawDescData = file_options_proto_rawDesc
)

func file_options_proto_rawDescGZIP() []byte {
	file_options_proto_rawDescOnce.Do(func() {
		file_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_options_proto_rawDescData)
	})
	return file_options_proto_rawDescData
}

var file_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_options_proto_goTypes = []interface{}{
	(*MessageOption)(nil),                // 0: protoc_gen_starlark_go.options.MessageOption
	(*MessageOption_CustomStarlark)(nil), // 1: protoc_gen_starlark_go.options.MessageOption.CustomStarlark
	(*descriptorpb.MessageOptions)(nil),  // 2: google.protobuf.MessageOptions
	(*descriptorpb.EnumOptions)(nil),     // 3: google.protobuf.EnumOptions
}
var file_options_proto_depIdxs = []int32{
	1, // 0: protoc_gen_starlark_go.options.MessageOption.custom:type_name -> protoc_gen_starlark_go.options.MessageOption.CustomStarlark
	2, // 1: protoc_gen_starlark_go.options.message_option:extendee -> google.protobuf.MessageOptions
	3, // 2: protoc_gen_starlark_go.options.enum_option:extendee -> google.protobuf.EnumOptions
	0, // 3: protoc_gen_starlark_go.options.message_option:type_name -> protoc_gen_starlark_go.options.MessageOption
	0, // 4: protoc_gen_starlark_go.options.enum_option:type_name -> protoc_gen_starlark_go.options.MessageOption
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_options_proto_init() }
func file_options_proto_init() {
	if File_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_options_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOption_CustomStarlark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_options_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*MessageOption_Disable)(nil),
		(*MessageOption_ToString)(nil),
		(*MessageOption_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_options_proto_goTypes,
		DependencyIndexes: file_options_proto_depIdxs,
		MessageInfos:      file_options_proto_msgTypes,
		ExtensionInfos:    file_options_proto_extTypes,
	}.Build()
	File_options_proto = out.File
	file_options_proto_rawDesc = nil
	file_options_proto_goTypes = nil
	file_options_proto_depIdxs = nil
}
